apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: bookstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_DB
          value: bookstore
        - name: POSTGRES_USER
          value: book
        - name: POSTGRES_PASSWORD
          value: book
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: bookstore
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
